server:
  port: 8080
  servlet:
    context-path: /coke
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    name: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot?useSSL=true
mybatis:
  type-aliases-package: cn.markedquilt.demo.login.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml